#!/usr/bin/with-contenv bash

cd /config

if [ -n "$GITHUB_TOKEN" ]; then
  exec s6-setuidgid abc java -jar /app/curseforgebot/curseforgebot.jar -github
else
  exec s6-setuidgid abc java -jar /app/curseforgebot/curseforgebot.jar
fi