#!/usr/bin/with-contenv bash

cd /app/curseforgebot

if [ -n "$GITHUB_TOKEN" ]; then
  exec s6-setuidgid abc java -jar curseforgebot.jar -github
else
  exec s6-setuidgid abc java -jar curseforgebot.jar
fi