#!/usr/bin/with-contenv bash

if [ ! -f /config/bot.conf ]; then
  cp -f \
    /defaults/bot.conf \
    /config/bot.conf
  sed -i \
    "s/DISCORD_BOT_TOKEN/&{DISCORD_BOT_TOKEN}/g" \
    /config/bot.conf
  sed -i \
    "s/DISCORD_CHANNEL_ID/&{DISCORD_CHANNEL_ID}/g" \
    /config/bot.conf
  sed -i \
    "s/PROJECT_ID/&{PROJECT_ID}/g" \
    /config/bot.conf
  if [ -z $ROLE_ID ]; then
    sed -i \
      "s/ROLE_ID/000000000/g" \
      /config/bot.conf
  else
    sed -i \
      "s/ROLE_ID/&{ROLE_ID}/g" \
      /config/bot.conf
  fi
  sed -i \
    "s/FILE_LINK/&{FILE_LINK}/g" \
    /config/bot.conf
  sed -i \
    "s/DESCRIPTION/&{DESCRIPTION}/g" \
    /config/bot.conf
  sed -i \
    "s/CHANGELOG_FORMAT/&{CHANGELOG_FORMAT}/g" \
    /config/bot.conf
  if [ -z $GITHUB_TOKEN ]; then
    sed -i \
      "s/GITHUB_TOKEN//g" \
      /config/bot.conf
  else
    sed -i \
      "s/GITHUB_TOKEN/&{GITHUB_TOKEN}/g" \
      /config/bot.conf
  fi
  if [ -z $GITHUB_REPO ]; then
    sed -i \
      "s/GITHUB_REPO/CurseforgeBotCache/g" \
      /config/bot.conf
  else
    sed -i \
      "s/GITHUB_REPO/&{GITHUB_REPO}/g" \
      /config/bot.conf
  fi
fi

ln -sf /config/bot.conf /app/curseforgebot/bot.conf